spring.application.name=firstSpringBoot

# 1. C?u hình k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=1234567
# Khai báo Driver c? th? (dành cho MySQL 8.0+)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. C?u hình JPA / Hibernate
# update: T? ??ng c?p nh?t b?ng d?a trên Entity (R?t t?t cho Beginner)
spring.jpa.hibernate.ddl-auto=update
# Hi?n th? câu l?nh SQL xu?ng console ?? b?n d? debug
spring.jpa.show-sql=true
# ??nh d?ng câu l?nh SQL cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
# Khai báo Dialect ?? Hibernate sinh SQL t?i ?u cho MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect